services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=cinema_db
      - DB_USER=cinema_user
      - DB_PASS=secretpassword
    depends_on:
      - db

volumes:
  postgres_data: